services:
  app:
    container_name: ${APP_NAME}-app
    image: ${APP_NAME}:latest
    env_file:
      - .env.develop
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
        POETRY_VERSION: ${POETRY_VERSION}
        PYTHON_IMAGE: ${PYTHON_IMAGE}
    depends_on:
      - db
    ports:
      - "8073:8073"
  db:
    container_name: ${APP_NAME}-db
    image: postgres:latest
    env_file:
      - .env.develop
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"