version: "3"

services:
  app:
    container_name: ${APP_NAME}
    image: ${APP_NAME}:latest
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
        POETRY_VERSION: ${POETRY_VERSION}
        PYTHON_IMAGE: ${PYTHON_IMAGE}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl --fail http://0.0.0.0:8000/health/ || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 1

    env_file:
      - .env.production
    ports:
      - ${PORT}:${PORT}

  db:
    container_name: tiny-db
    image: postgres
    env_file:
      - .env.base
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"