"""empty message

Revision ID: e2155a03cd80
Revises: cd2d34f2568d
Create Date: 2025-01-26 00:08:44.235594

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2155a03cd80"
down_revision: str | None = "cd2d34f2568d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readiness_statuses",
        sa.Column("hostname", sa.String(length=128), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
    )
    op.drop_table("rediness_statuses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rediness_statuses",
        sa.Column(
            "hostname", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("ready", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="rediness_statuses_pkey"),
        sa.UniqueConstraint("hostname", name="rediness_statuses_hostname_key"),
    )
    op.drop_table("readiness_statuses")
    # ### end Alembic commands ###
